steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: Azure for Students(40e8f6d0-3344-46b2-b963-30ae2661fbae)
    appType: webAppLinux
    appName: java-app-fiap
    package: $(System.DefaultWorkingDirectory)/**/*.zip
    runtimeStack: JAVA|17-java17
  trigger:
    - main
  pool:
    vmImage: ubuntu-latest
  steps:
    - task: Maven@4
      inputs:
        mavenPomFile: pom.xml
        mavenOptions: '-Xmx3072m'
        javaHomeOption: JDKVersion
        jdkVersionOption: '1.8'
        jdkArchitectureOption: x64
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        goals: package
